"""Persona prompt generation from decoded personas (Phase 3, Layer 1 only).

Reads ../dataset_analysis/outputs/phase2_decoded_personas.json (produced by the
dataset_analysis/ subproject) and turns each left/right pole persona into a
Layer 1 (ideological identity) system prompt for a debate agent, in English,
with no dataset provenance inside the prompt text itself — the prompt names
neither the source dataset nor the record it came from. Provenance and
selection metadata are persisted separately in persona_metadata.json.

Political-lean blinding: neither the `political_lean` attribute nor the pole
label ("left pole" / "right pole") is written into the prompt text. The persona
is described only by its substantive issue positions, so that the model derives
its stance from those positions instead of role-playing a label. Both values are
still recorded in persona_metadata.json — the blinding applies to the agent, not
to us.

Layer 2 (debate behavior instructions) is handled elsewhere and is not
generated by this script.

This script makes no API/LLM calls — it only generates text from the already
decoded categorical attributes.

Prerequisite:
- ../dataset_analysis/outputs/phase2_decoded_personas.json

Outputs:
- outputs/prompts/personas/persona_metadata.json   (list of 20 metadata dicts)
- outputs/prompts/personas/polo_direita/persona_NN.txt
- outputs/prompts/personas/polo_esquerda/persona_NN.txt
"""

import json
import sys
from pathlib import Path

DECODED_PERSONAS_PATH = Path("../dataset_analysis/outputs/phase2_decoded_personas.json")

PROMPTS_ROOT = Path("outputs/prompts/personas")
OUT_METADATA_JSON = PROMPTS_ROOT / "persona_metadata.json"

PROMPT_VERSION = "v2.1"

# Attributes deliberately withheld from the prompt text. They stay in
# persona_metadata.json for analysis, pairing and auditing.
BLINDED_ATTRIBUTES = ("political_lean",)

# English labels for each categorical dimension, in template order. Fields
# absent or null in a given persona record are omitted from the prompt, as are
# the fields listed in BLINDED_ATTRIBUTES.
ATTRIBUTE_LABELS = {
    "religiosity": "religiosity",
    "trust_level": "institutional trust level",
    "values_priority": "core value",
    "att_free_markets": "stance on free market",
    "att_government_regulation": "stance on government regulation",
    "att_labor_unions": "stance on labor unions",
    "att_immigration": "stance on immigration",
    "att_gun_ownership": "stance on gun ownership",
    "att_capital_punishment": "stance on capital punishment",
}

POLE_LABELS = {
    "polo_esquerda_political_lean": ("left", "left pole", "polo_esquerda"),
    "polo_direita_political_lean": ("right", "right pole", "polo_direita"),
}


def check_prerequisite() -> dict:
    if not DECODED_PERSONAS_PATH.exists():
        print(f"[ERRO] {DECODED_PERSONAS_PATH} não encontrado.")
        print("Execute primeiro (a partir de dataset_analysis/):")
        print("  cd ../dataset_analysis && uv run python scripts/03_decode_attributes.py")
        sys.exit(1)
    try:
        return json.loads(DECODED_PERSONAS_PATH.read_text())
    except json.JSONDecodeError as e:
        print(f"[ERRO] {DECODED_PERSONAS_PATH} não é JSON válido: {e}")
        sys.exit(1)


def build_prompt(persona: dict, pole_key: str, pole_label: str, index: int) -> dict:
    attrs = persona.get("political_attributes", {})

    lines = [
        "You are a debate persona.",
        "",
        "Your positioning is defined by the following attributes:",
    ]

    for attr_id, label in ATTRIBUTE_LABELS.items():
        if attr_id in BLINDED_ATTRIBUTES:
            continue
        value = attrs.get(attr_id)
        if value is None:
            continue
        lines.append(f"- {label}: {value}")

    lines.append("")
    lines.append(
        "Debate in strict accordance with these attributes, maintaining "
        "positional consistency throughout the entire conversation. "
        "When confronted with topics not directly covered by the attributes "
        "above, derive your position coherently from your listed values "
        "without contradicting them. Do not invent attributes."
    )

    prompt_text = "\n".join(lines)

    metadata = {
        "pole": pole_key,
        "pole_label": pole_label,
        "persona_index": index,
        "matraix_source": persona.get("source"),
        "matraix_id": persona.get("source_record_id"),
        "prompt_version": PROMPT_VERSION,
        # Withheld from the prompt text, kept here for pairing and analysis.
        "blinded_attributes": {
            attr_id: attrs.get(attr_id) for attr_id in BLINDED_ATTRIBUTES
        },
    }

    return {"prompt": prompt_text, "metadata": metadata}


def main() -> int:
    decoded = check_prerequisite()

    PROMPTS_ROOT.mkdir(parents=True, exist_ok=True)

    all_metadata = []
    total_generated = 0

    for json_key, (pole_key, pole_label, dir_name) in POLE_LABELS.items():
        personas = decoded.get(json_key, [])
        if not personas:
            print(f"[AVISO] Nenhuma persona encontrada em '{json_key}'.")
            continue

        pole_dir = PROMPTS_ROOT / dir_name
        pole_dir.mkdir(parents=True, exist_ok=True)

        for i, persona in enumerate(personas):
            result = build_prompt(persona, pole_key, pole_label, i)
            filename = f"persona_{i:02d}.txt"
            (pole_dir / filename).write_text(result["prompt"])

            all_metadata.append(result["metadata"])
            total_generated += 1

        print(f"[OK] {len(personas)} prompts gerados para '{pole_key}' em {pole_dir}/")

    OUT_METADATA_JSON.write_text(json.dumps(all_metadata, indent=2, ensure_ascii=False))
    print(f"[OK] Total de {total_generated} prompts gerados.")
    print(f"[OK] Metadados salvos em {OUT_METADATA_JSON}")

    if total_generated == 0:
        print("[ERRO] Nenhum prompt foi gerado — verifique outputs/phase2_decoded_personas.json.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
